### PR TITLE
Added social media links to the website

### LINKED ISSUE #26: Add Social Links, Github, and discord links to web site

### PR DESCRIPTION
**Pull request by anuragh2002**
Closes #26 

Added social media links for Youtube, Twitter, Instagram, Discord and LinkedIn to the website both in header and footer.

### CODE REVIEW

**Review by dewanshDT — APPROVED** [review]
noice!!

**Comment by dewanshDT** [comment]
nice work bro!!

**Comment by dewanshDT** [comment]
@anuragh2002 also add you contribution details in contribution.json file so that it'll be showcased

**Comment by anuragh2002** [comment]
Yeah, sure, thanks I will!

**Pull request merged**
